[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
eframe = "0.26.0"
egui = "0.26.0"
peekmore = "1.3.0"
pyo3 = "0.20.2"
